#!/bin/sh

# Configure the values for XDG
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=$HOME/.config}
export XDG_DATA_HOME=${XDG_DATA_HOME:=$HOME/.local/share}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:=$HOME/.cache}

# Configure the values for GTK
export GTK_RC_FILES=${GTK_RC_FILES:=$XDG_CONFIG_HOME/gtk-1.0/gtkrc}
export GTK2_RC_FILES=${GTK2_RC_FILES:=$XDG_CONFIG_HOME/gtk-2.0/gtkrc}

# Configure TMPDIR
export TMPDIR=${TMPDIR:=/tmp}

# Configure X11
export XINITRC=${XINITRC:=$XDG_CONFIG_HOME/X11/xinitrc}
export XSERVERRC=${XSERVERRC:=$XDG_CONFIG_HOME/X11/xserverrc}
export ERRFILE=${ERRFILE:=$TMPDIR/xsession-errors-$USER}

# Configure Golang
export GOPATH=${GOPATH:=$XDG_DATA_HOME/go}

# Configure PATH
export PATH=$PATH:$GOPATH/bin

# PATH for ZSH config files
export ZDOTDIR=${ZDOTDIR:=$XDG_CONFIG_HOME/zsh}
